export const products = [
  {
    id: 1,
    img: "https://github.com/safak/restaurant-ui/blob/main/public/temporary/p1.png?raw=true",
    title: "food title",
    desc: "food desc Learn how to create a horizontal scrollable menu with CSS. Learn how to create a horizontal scrollable menu with CSS. Learn how to create a horizontal scrollable menu with CSS.",
    price: 29,
    category: "pizza",
  },
  {
    id: 2,
    img: "https://github.com/safak/restaurant-ui/blob/main/public/temporary/p10.png?raw=true",
    title: "food title",
    desc: "food desc Learn how to create a horizontal scrollable menu with CSS. Learn how to create a horizontal scrollable menu with CSS. Learn how to create a horizontal scrollable menu with CSS.",
    price: 29,
    category: "pizza",
  },
  {
    id: 3,
    img: "https://github.com/safak/restaurant-ui/blob/main/public/temporary/p11.png?raw=true",
    title: "food title",
    desc: "food desc Learn how to create a horizontal scrollable menu with CSS. Learn how to create a horizontal scrollable menu with CSS. Learn how to create a horizontal scrollable menu with CSS.",
    price: 29,
    category: "pizza",
  },
  {
    id: 4,
    img: "https://github.com/safak/restaurant-ui/blob/main/public/temporary/p12.png?raw=true",
    title: "food title",
    desc: "food desc Learn how to create a horizontal scrollable menu with CSS. Learn how to create a horizontal scrollable menu with CSS. Learn how to create a horizontal scrollable menu with CSS.",
    price: 29,
    category: "pizza",
  },
  {
    id: 5,
    img: "https://github.com/safak/restaurant-ui/blob/main/public/temporary/p2.png?raw=true",
    title: "food title",
    desc: "food desc Learn how to create a horizontal scrollable menu with CSS. Learn how to create a horizontal scrollable menu with CSS. Learn how to create a horizontal scrollable menu with CSS.",
    price: 29,
    category: "burger",
  },
  {
    id: 6,
    img: "https://github.com/safak/restaurant-ui/blob/main/public/temporary/p3.png?raw=true",
    title: "food title",
    desc: "food desc Learn how to create a horizontal scrollable menu with CSS. Learn how to create a horizontal scrollable menu with CSS. Learn how to create a horizontal scrollable menu with CSS.",
    price: 29,
    category: "pizza",
  },
  {
    id: 7,
    img: "https://github.com/safak/restaurant-ui/blob/main/public/temporary/p4.png?raw=true",
    title: "food title",
    desc: "food desc Learn how to create a horizontal scrollable menu with CSS. Learn how to create a horizontal scrollable menu with CSS. Learn how to create a horizontal scrollable menu with CSS.",
    price: 29,
    category: "pasta",
  },
  {
    id: 8,
    img: "https://github.com/safak/restaurant-ui/blob/main/public/temporary/p5.png?raw=true",
    title: "food title",
    desc: "food desc Learn how to create a horizontal scrollable menu with CSS. Learn how to create a horizontal scrollable menu with CSS. Learn how to create a horizontal scrollable menu with CSS.",
    price: 29,
    category: "burger",
  },
  {
    id: 9,
    img: "https://github.com/safak/restaurant-ui/blob/main/public/temporary/p6.png?raw=true",
    title: "food title",
    desc: "food desc Learn how to create a horizontal scrollable menu with CSS. Learn how to create a horizontal scrollable menu with CSS. Learn how to create a horizontal scrollable menu with CSS.",
    price: 29,
    category: "pizza",
  },
];

export const categories = [
  {
    id: 1,
    img: "https://github.com/safak/restaurant-ui/blob/main/public/temporary/m1.png?raw=true",
    title: "menu title",
    desc: "menu desc",
    category: "pasta",
  },
  {
    id: 2,
    img: "https://github.com/safak/restaurant-ui/blob/main/public/temporary/m2.png?raw=true",
    title: "menu title",
    desc: "menu desc",
    category: "burger",
  },
  {
    id: 3,
    img: "https://github.com/safak/restaurant-ui/blob/main/public/temporary/m3.png?raw=true",
    title: "menu title",
    desc: "menu desc",
    category: "pizza",
  },
];
